# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(692, 576)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(3, 1, 691, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(50, 20, 121, 20))
        self.lineEdit.setObjectName("lineEdit")
        file = open("info.txt","r")
        add = file.readline()
        self.lineEdit.setText(add[0:-1])  
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 20, 51, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 20, 121, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        name = file.readline()
        self.lineEdit_2.setText(name[0:-1])
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(400, 20, 41, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(440, 20, 131, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        code = file.readline()
        self.lineEdit_3.setText(code[0:-1])
        file.close()
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(600, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, 60, 691, 161))
        self.textBrowser.setObjectName("textBrowser")
        #self.verticalSlider = QtWidgets.QSlider(Dialog)
        #self.verticalSlider.setGeometry(QtCore.QRect(670, 60, 19, 160))
        #self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        #self.verticalSlider.setObjectName("verticalSlider")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(320, 40, 81, 21))
        self.label_5.setObjectName("label_5")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(0, 250, 681, 192))
        self.listView.setObjectName("listView")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 455, 61, 21))
        self.label_6.setObjectName("label_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(70, 450, 541, 21))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(320, 230, 54, 12))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 480, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 480, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 480, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(570, 480, 121, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 530, 111, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 530, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 530, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(570, 530, 121, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.login)
        self.pushButton_2.clicked.connect(Dialog.back)
        self.pushButton_3.clicked.connect(Dialog.enter)
        self.pushButton_4.clicked.connect(Dialog.rename)
        self.pushButton_5.clicked.connect(Dialog.create)
        self.pushButton_6.clicked.connect(Dialog.upload)
        self.pushButton_7.clicked.connect(Dialog.download)
        self.pushButton_8.clicked.connect(Dialog.delete)
        self.pushButton_9.clicked.connect(Dialog.quit)
        self.listView.doubleClicked.connect(Dialog.clicked)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">QQFTP客户端</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>主机：</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "用户名："))
        self.label_4.setText(_translate("Dialog", "密码："))
        self.pushButton.setText(_translate("Dialog", "登录"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">客户端状态</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "详细信息："))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">文件列表</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "回到上一级目录"))
        self.pushButton_3.setText(_translate("Dialog", "进入下一级目录"))
        self.pushButton_4.setText(_translate("Dialog", "文件重命名"))
        self.pushButton_5.setText(_translate("Dialog", "创建新文件"))
        self.pushButton_6.setText(_translate("Dialog", "上传文件"))
        self.pushButton_7.setText(_translate("Dialog", "下载文件"))
        self.pushButton_8.setText(_translate("Dialog", "删除文件"))
        self.pushButton_9.setText(_translate("Dialog", "退出客户端"))

